Fix no-artist listed
Adds support to check for 1 (or more) composers, or DJs, in lieu of a torrent having no artist and thus an empty artist array.

Prevents Traceback (most recent call last):
  File "/app/redactedbetter", line 293, in <module>
    main()
  File "/app/redactedbetter", line 158, in main
    if len(group['group']['musicInfo']['artists']) > 1:
TypeError: 'NoneType' object has no attribute '__getitem__'